### ISSUE TITLE
export at the beginning

### ISSUE THREAD

**Issue by fanatid** [mafintosh/random-access-file#3]
Sorry, it is not best place for this question, but

why you export from file in [beginning](https://github.com/mafintosh/random-access-file/blob/93fbac7d52800d3b0ed94170e167330b932bb32a/index.js#L7) instead at the end? (you did this two years ago [mafintosh/objectstruct](https://github.com/mafintosh/objectstruct/blob/f88cb7d66f18df365f584b3700845f8b4fa1476c/index.js#L95)) It solves some kind of problem? It's more clear?

**Comment by mafintosh** [comment]
My style is continuously changing over time. I put exports in the beginning now so they are grouped with requires. I currently like that. I'm also influenced by the style of people I work with like @maxogden and @feross

**Comment by fanatid** [comment]
@mafintosh thank you for the answer
I think it's a good reason (grouped with requires) for export in file beginning.
